apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: marketx-backend-secrets
  labels:
    app: marketx-backend-secrets
    component: secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:marketx_env-eBi9Bu
        objectAlias: ".env"
        objectType: "secretsmanager"
