 apiVersion: v1
 kind: Service
 metadata:
   name: marketx-frontend
 spec:
   selector:
     app: marketx-frontend
   ports:
     - name: http
       port: 80
       targetPort: 80
   type: ClusterIP
