 apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization
 
 namespace: marketx
 
 resources:
   - secrets-store/marketx-frontend-secrets-spc.yaml
   - deployment/frontend-deployment.yaml
   - services/frontend-service.yaml
   - ingress/frontend-ingress.yaml
   - autoscaling/frontend-hpa.yaml
