 apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization
 
 namespace: marketx
 
 resources:
   - ../../base
 
 images:
   - name: marketx-frontend
     newName: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/marketx-frontend
     newTag: latest
