 apiVersion: v1
 kind: Secret
 metadata:
   name: marketx-backend-secrets
 type: Opaque
 stringData:
   DATABASE_URL: "postgresql://desinguraja:admin@123@35.154.188.143:5432/marketx"
   REDIS_URL: "redis://marketx-redis:6379/0"
   SECRET_KEY: "_1=n^f0*=jr5%kc@(u=hd3kp-_u1!z_s(5cxa2ex59y3s9o*8-"
   DJANGO_SETTINGS_MODULE: "config.settings.production"
   DEBUG: "False"
   ALLOWED_HOSTS: "heycampus.io,www.heycampus.io"
   CORS_ALLOWED_ORIGINS: "https://heycampus.io,https://www.heycampus.io"
   AWS_STORAGE_BUCKET_NAME: "marketx-greatify"
   AWS_S3_REGION_NAME: "ap-south-1"
