 apiVersion: v1
 kind: Secret
 metadata:
   name: marketx-backend-secrets
 type: Opaque
 stringData:
   DATABASE_URL: "postgresql://USER:PASSWORD@HOST:5432/DBNAME"
   REDIS_URL: "redis://marketx-redis:6379/0"
   SECRET_KEY: "change-me"
   DJANGO_SETTINGS_MODULE: "config.settings.production"
   DEBUG: "False"
   ALLOWED_HOSTS: "heycampus.io,www.heycampus.io"
   CORS_ALLOWED_ORIGINS: "https://heycampus.io,https://www.heycampus.io"
   AWS_STORAGE_BUCKET_NAME: "marketx-greatify"
   AWS_S3_REGION_NAME: "ap-south-1"
